version: '2'
services:
  
  nginx:
    image: viniciusmattosrj/nginx
    restart: always
    volumes:
     - ../nginx/nginx_conf/:/etc/nginx/conf.d
    volumes_from:
     - php:rw
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.10
    container_name: nginx_projetos

  php: #php7.1.15
    image: viniciusmattosrj/php:7.1
    command: bash -c "sed -i \"s/short_open_tag = Off/short_open_tag = On/\" /usr/local/etc/php/php.ini
                && sed -i \"s/register_argc_argv = Off/register_argc_argv = On/\" /usr/local/etc/php/php.ini
                && sed -i \"s/max_execution_time = 30/max_execution_time = 80000000/\" /usr/local/etc/php/php.ini
                && sed -i \"s/upload_max_filesize = 2M/upload_max_filesize = 30M/\" /usr/local/etc/php/php.ini
                && sed -i \"s/max_input_time = 60/max_input_time = 80000000/\" /usr/local/etc/php/php.ini
                && sed -i \"s/;date.timezone =/date.timezone = America\/Sao_Paulo/\" /usr/local/etc/php/php.ini
                && sed -i \"s/;sendmail_path =/sendmail_path = \/usr\/bin\/mhsendmail --smtp-addr mailhog:1025/\" /usr/local/etc/php/php.ini
                && sed -i \"s/post_max_size = 8M/post_max_size = 31000M/\" /usr/local/etc/php/php.ini && php-fpm"
    container_name: php
    environment:
     - XDEBUG_CONFIG=remote_host=172.17.0.1
     - PHP_IDE_CONFIG=serverName=Local
    volumes:
     - ./:/var/www/html
     - ~/.ssh:/root/.ssh
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.11

networks:
  projetos_servicos:
   external: true
